### ISSUE TITLE
"How To": Upgrade Allegro 4 to 5

### ISSUE THREAD

**Issue by lonegraywolf2000** [ZQuestClassic/ZQuestClassic#13]
This is meant as a "sibling" of #11 here: in order for Allegro to play nice with Windows, we have to play nice with Allegro.

I've done some initial scouting on how we can use a modern, up to date version of Allegro. It would really help with building on Windows, especially for those that prefer using the MSVC tools.

The #allegro channel on Freenode took a quick gander at the source code to get an idea. Most of the graphics calls we make should be convert-able with some A4 to A5 tool that was made. Manual steps are also provided [on their wiki](https://wiki.allegro.cc/index.php?title=Porting_from_A4_to_A5). However, the biggest issue is that instead of drawing on bitmaps and bliting them (or drawing sprites) to the screen, you write to the screen the entire time. The dialog box features...there was some slight disagreement as to whether they could be directly converted or not, but it shouldn't be too difficult to come up with something new if necessary. The big one deals with pixel manipulation.

In looking at `tiles.cpp`, a lot of lines in the form of `b->line[y][x]` were noticed. That's a general pattern for accessing pixels directly in memory. In Allegro 5, that can't be done right away: instead, the bitmap would have to be "locked", manipulated, and then "unlocked". It's likely to be a slow operation. Instead, it was suggested to use the new primitives Allegro 5 brought, and/or utilize pixel shaders.

The A4 to A5 tool does not work with palettes or direct bitmap access. That is what has to be worked around. Everything else should have an automatic or clearly stated conversion. If we solve the palette/bitmap issue, Allegro 5 will work for us.

**Comment by Gleeok** [comment]
Another problem is how ZC renders, in general. Even though allegro5 is hardware accelerated there may be a very significant performance drop due to massive driver overhead. OpenGL 2.1 shaders plus FBO extensions might be the minimum requirements to even get playable frame rates.

Then again, I'm always a bit cynical on the 'is it easier to rewrite it or not' topic.

**Comment by lonegraywolf2000** [comment]
Is there a way to test or benchmark that theory? Also, if the minimums have increased due to these extensions and shaders...what does that make the minimum? I don't know how much of the older OSes you want to support.

**Comment by Gleeok** [comment]
allegro4 to 5 is a significant amount of work. Saffith already started working on the GUI but he's still not done yet. 

Not trying to dissuade anyone though! :) ...Just pointing out some things that will need a redesign.

**Comment by zeromus** [comment]
leave the old allegro, use new SDL, use old allegro's BITMAP stuff to generate a software frame to ship off to SDL instead of letting allegro display it. your stuff is basically low resolution, so you can still get 1000 fps. nothing essential has to change from how it works now except you're on a more modern codebase. nobody will like what happens if you try to hardware accelerate anything with HW primitives and shaders, it will screw everything up.

intermediate milestone: dump frames as bmps on a windowless version of the program.

incidentally, I'll be essentially doing this anyway, if I fix this engine to run in retroarch. I'm not sure I'll take it that far though.

**Comment by evouga** [comment]
I tend to agree with zeromus: I don't think there much need to hardware-accelerate ZC's rendering, and using hardware surfaces rather than textures causes all manner of trouble (see: current fullscreen bugs).

But in any case how to revamp ZC's rendering code is a topic for extended discussion on the forums. Closing this issue for now as there are no near-term plans to port to Allegro 5.
