### ISSUE TITLE
Zquest on android with dosbox

### ISSUE THREAD

**Issue by Astromatik** [ZQuestClassic/ZQuestClassic#189]
Hello
I get zquest 2.10 and I try to open it with dosbox turbo and retroarch on my xperia Zx Premium. 
The load I'd data files:
Zquest. Dat... Failed
Any issues? 
I think zelda classic on android it s very good, and 4k screen... Would love it!

**Comment by Astromatik** [comment]
![screenshot_20180112-235750](https://user-images.githubusercontent.com/32705512/34898683-9b869928-f7f4-11e7-9827-d150a9ac0725.png)

**Comment by Astromatik** [comment]
Do you know What s going on ?

**Comment by Astromatik** [comment]
Can you help me please

**Comment by Astromatik** [comment]
Please i very need help for start zquest on dosbox. 2 mounth i try it...

**Comment by ZoriaRPG** [comment]
@Astromatik 
There is no  official support for running ZC on DOSBox (any platform). You would be better-off asking on the forum (http://www.armageddongames.net), as some members  there have done this with old/outdated ZC versions. 

I am not an expert on DOSBox (at all), and I file it in the same category as WINE. Stuff either works, or does not work. I suspect that the Android build of DOSBox is quite limiting, compared to the PC version, which is enough of a pain to configure.

Further, use of 2.10.x and earlier versions have very limited legacy support. The quest formats are supported in modern ZC builds (2.50.x, 2.53, and 2.54 can all run 2.10 quests), but there is almost no support for running DOS builds of ZC/ZQuest. I do not have a system with MS-DOS/PC-DOS running on it at present, and if I did, it would likely be too old to run ZC (386SX-16).

There is a source pack available for 2.10.x  if you want *that*, but otherwise, this isn't a code issue. 

AndroidOS is not a supported target platform, as Allegro4 doesn't run on it natively. Using emulators isn't officialy supported, although VM use *is*.

ZC/ZQuest (2.53.0 and higher) should work on the GPD Win (https://en.m.wikipedia.org/wiki/GPD_Win), if you want a hardware device for ZC that is pocket-sized. 

(I do not yet own one, to test this theory.)

**Comment by ZoriaRPG** [comment]
ZC/ZQuest (2.53.0 and higher) should work on the GPD Win (https://en.m.wikipedia.org/wiki/GPD_Win), if you want a hardware device for ZC that is pocket-sized.

**Comment by Astromatik** [comment]
OK i don t try VM thank you

**Comment by ZoriaRPG** [comment]
@Astromatik

You might want to try some other PC emulators. There is no way to virtualise non-i686 hardware with a VM, to run i686 software.

(https://play.google.com/store/apps/details?id=fr.energycube.android.app.com.limbo.emu.main.armv7&hl=en_US)

That looks viable. There is also a QEmu port for Android. My device is not likely powerful-enough to suitably run *either of these*.

You will want to emulate W95 for ZC 2.10, and Windows Vista/XP for 2.50, should you wish to try this route. (It's still unsupported.)

**Comment by ZoriaRPG** [comment]
For anyone who cares: 2.10-Win runs just peachy with DXGL.
