### ISSUE TITLE
Audio is crackling and stuttering on Debian Jessie with Pulseaudio

### ISSUE THREAD

**Issue by kadogo** [ZQuestClassic/ZQuestClassic#38]
Hello everyone,

My OS is Debian Jessie x64 with Pulseaudio.
In case it's important, I use an usb audio device.

When I launch the game and look in pavucontrol, it look like the sound playback go up and down.
To stabilize it I need to turn off my device and set it on again.
After a few times I have the sound correctly.

I use only pulseaudio so I don't know if we have the same problem with pure alsa or oss.

Cheers.

**Comment by evouga** [comment]
This is using the 2.50.2 binaries from zeldaclassic.com?

**Comment by kadogo** [comment]
Hello, I just download the last version from zeldaclassic.com to be sure and I have the same problem.

**Comment by kadogo** [comment]
Hello,

I repost to say that I have try some solution with alsa-oss but the problem is always the same.
If I run ZC 2.5.2 with wine it's working without any issues (not sure it help, but maybe).

**Comment by marcxjo** [comment]
I can confirm this across several development builds of ZC2.50 (as far back as Build 1125), the 2.50.2 builds, and the 2.50.3rc builds on Fedora 27 x86_64. `htop` shows that Xorg CPU usage spikes while playing. Note that it drops significantly and audio stops stuttering as soon as I hide or minimize the window.

For what it's worth, I didn't have this issue the last time I used an all-32-bit Slackware chroot with PulseAudio installed on some of the earlier builds I have available. That would have been probably about 3 to 4 years ago. I don't have access to that kind of chroot at the moment, but I'll test when I do (probably a week or two out).

For anyone else who's interested, a 32-bit native OS or chroot environment might be a good place to start looking for a test case where this issue doesn't occur.

**Comment by marcxjo** [comment]
Minimizing, hiding, or switching away from the ZC window's current workspace immediately causes audio to stabilize and play at a normal speed with no crackling at all. `htop` shows that Xorg CPU consumption goes nuts whenever the window is visible. I can easily see 100% usage on at least one core within seconds of starting a quest.

I've tested this in several environments of varying "heaviness" in terms of resource consumption and sheer graphical complexity; this is extremely noticeable and problematic on GNOME 3.26 running on both X and Wayland (where compositing is always on and the latency is significantly worse than on any other platform tested), but still non-trivial and annoying on an environment as minimal as bspwm with no compositing (though note that killing Compton immediately shows a visible and lasting improvement).

The problem is visible in every resolution, but gets worse with increasingly larger windowed resolutions. In fullscreen, the problem won't emerge for several seconds (usually 10-15), but eventually performance degrades to a level comparable with ~640x480 res.

Hope this helps provide some insight.

**Comment by marcxjo** [comment]
I've had the chance to run a 32-bit chroot and test the results. It's the same story. Audio crackles and stutters until you hide the window or change to a workspace that doesn't show it. Xorg CPU usage goes nuts while the window is visible. This happens even on older versions from before I was able to get this working pain-free back in 2014/15-ish, so the issue may well have to do with recent versions of Xorg.

**Comment by marcxjo** [comment]
Also worth noting is that this definitely still happens with pure ALSA. Haven't tried OSS, but I don't see much point anyway at this point. It almost certainly seems to be an Xorg issue.

**Comment by marcxjo** [comment]
Setting `vsync = 1` under [zeldadx] fixes this issue entirely for me. Interestingly enough, this works even if not using a vsync-enabled compositor, or any compositor at all.

@kadogo, check your ag.cfg and see if this helps.

At least for me, though, the Linux build is still hella slow for any res above 640x480. This just happens to address the crackly audio.

**Comment by kadogo** [comment]
@marcxjo 
Sorry it took me long time to try ZC again.

I just download the latest stable version and setting vsync = 1 in ag.conf not really help for me.
I have the feeling than changing the resolution change the "cracklings" but at 640x480 it not stop crackeling.

**Comment by ghost** [comment]
EDITED:
~~THE SOLUTION: They are missing dependencies~~

~~On ubuntu 18.04~~
~~`sudo apt install libatk-adaptor:i386 libatk-bridge2.0-0:i386 libcanberra-gtk-module:i386 appmenu-gtk2-module:i386`~~

~~Now, it works as intended. Some dependencies might still be missing.~~

-_- beh... I rebooted, and it doesn't work now....

**Comment by ghost** [comment]
This dates back to December 2016. A flatpack/snap/appimage might mask the problem.

**Comment by ghost** [comment]
This problem is not present in ubuntu 20.04

**Comment by connorjclark** [comment]
Closing this for now, but when we re-release a linux build please file a new issue for any sound problems.
