### ISSUE TITLE
Repository has 450+ branches

### ISSUE THREAD

**Issue by mzxrules** [ZQuestClassic/ZQuestClassic#476]
the number of branches on the repository is excessive and makes it difficult to locate what is actively being worked on.

**Comment by ZoriaRPG** [comment]
I moved the branches that are merged or abandoned into work/*

The core development branches are 2.53, and 2.55.
Everything else that is active is either a version branch (frozen at a specific state, such as 2.53.0, 2.50.2, 2.10.1), a feature branch that is unfinished, or archival material under work and backups. 

Please also see:
https://github.com/ArmageddonGames/ZeldaClassic/branches
https://github.com/ArmageddonGames/ZeldaClassic/branches/active

The default branch is our current master branch for 2.55. As we are still updating 2.53 for the next 3 1/2 years, expect to see some commits to it as well, and when we have a new version of 2.53 out, then that gets a branch of its own, so that it is possible and easy to compare changes across released and gamma builds.
