### ISSUE TITLE
Xinput support - is this planned in the long run?

### ISSUE THREAD

**Issue by Gagert** [ZQuestClassic/ZQuestClassic#516]
On modern Windows 10 PCs, xinput devices has been the de facto gamepads for quite some time (Xbox 360 and Xbox One gamepads). However, it seems like Zelda Classic may be using an older/different input api for gamepads on Windows, my quess is direct input (since I can't bind the d-pad on my wireless Xbox One gamepad).

As of now I'm using a gamepad wrapper called Xinput Plus to use all the buttons of my Xbox One gamepad with Zelda Classic.

Are there any plans of xinput support for Zelda Classic?

**Comment by ZoriaRPG** [comment]
Input is 100% Allegro, which does indeed use DI. 

We bundle Antimicro for people with controllers that Allegro fails to support, along with configs specifically for the XBoxOne and the XBox360 controllers. You should be able to run Antimicro, load the config profile for your gamepad, and immediately use it.

In the future, when we can use some Ag5 features, we may look into another mechanism for input. 

You can find Antimicro, and the controller definitions in the ./Addons path in 2.53.1 and in 2.55. If you need it for 2.53.0, you can download 2.53.1 from zc.com and copy it over. There is no need to install anything: We included a 'standalone' version of Antimicro, so that you can run it direct from the ZC paths.
