### ISSUE TITLE
Any plans of porting Zelda Classic over to libretro (the format RetroArch uses)?

### ISSUE THREAD

**Issue by Gagert** [ZQuestClassic/ZQuestClassic#519]
I don't know how familiar any of you are with RetroArch, which is the official frontend to the libretro api. I suppose RetroArch is mostly known for emulators and such, the nice thing being that it unifies things such as gamepad configs, display output, user interface and so on, with an integrated online updater to get the newest versions of the libretro cores itself.

Maybe Zelda Classic could get a bit more exposure if it was ported over to the libretro api?

**Comment by barbudreadmon** [comment]
FWIW, i can provide help with the implementation if the author is interested. It should be feasible if : 
- sound can be exposed through some kind of ptr
- video can be exposed through some kind of ptr
- you can call a function to run 1 frame

I guess `romview` and `zquest` are tools than can't be ported anyway, it would be mostly about porting the player (without needing the `zcsound` library, which is the reason for the x86_32 only compatibility ?)

**Comment by ChristianSilvermoon** [comment]
This would really be one of the best things for ZeldaClassic, hope this happens for sure.

**Comment by liberodark** [comment]
A great project is available : https://github.com/netux79/zc210-libretro

**Comment by Darknior** [comment]
Yes for sure this project is excellent and working fine. I'm using it on Linux 64bit and it run perfectly.
Where i can't build fine the real officiel engine ...
Games running fine, but not the 2.50 one because the author has choose to port an older engine version.
And it's like OpenBOR, you must use the build of each game to run it, not really compatible with new engine ... 
Here like he write some one will must port the 2.5 version in an other core, or add it in parallel with a core option to switch version by game.
He has also remove some options like external MP3 OGG music files ... maybe it can also do a cool core option to support them, and cheats :)

For sure Retroarch will help ZeldaClassic to be more popular ... Libretro now is every where :)
And i love your engine i really wish it come on libretro to help users to use it :)

**Comment by connorjclark** [comment]
Not sure what the ask is here. The code is all available, and recently the entire program and its dependencies can be compiled from source easily. The Mac/web port work also made the code more portable.

There's no "run a single frame" logic. The main thread blocks on a timer set to 30 or 60 bps, but I suppose if you wanted to you could replace that timer controlling the blocking variable with a procedure call. Search for "myvsync"

**Comment by dxgldotorg** [comment]
I wonder if the recent port to a newer version of Allegro could make porting to libretro any easier.
