### ISSUE TITLE
MacOS app improvements

### ISSUE THREAD

**Issue by waldnzwrld** [ZQuestClassic/ZQuestClassic#61]
- [ ] MacOS app should use MacOS app style defaults
    - Move files (quests logs saves etc) to ~/Library/Application\ Support/Zelda\ Classic
    - Use MacOS notification to ask 'Are you sure' When quitting

Will update further as noticed

**Comment by ZoriaRPG** [comment]
Hmm... Have you looked at how jwin works? COnverting ZC to use system APIs instead of jwin is a gigantic undertaking. While we have tentative backends under way, it is unlikely that this would occur in the relative near future. 

At present, merely building an OSX version is an issue, and I need to buy some (commercial) software, solely to package ZC to work with OSX 10.11 and above.

I do still want to do a PPC build for 10.4 or 10.5, for sheer personal gratification.

**Comment by evouga** [comment]
Zoria is right that the GUI isn't something we can easily change.

The paths should be easy to modify, though I do not know enough about Macs to confidently make that change. Is the folder that should be used always relative to the executable's directory? Or some separate absolute path?

**Comment by waldnzwrld** [comment]
> Zoria is right that the GUI isn't something we can easily change. 

👍 

>  Is the folder that should be used always relative to the executable's directory? Or some separate absolute path?

In MacOS the directory used for supplemental files in any application is `/Users/[userName]/Library/Application\ Support/[appName]`   

This [stack overflow response](https://stackoverflow.com/a/9553507) may be a straight-forward answer. 

BTW @ZoriaRPG I am using MacOS 10.12.5 and the current ZC build works fine for me.

**Comment by kanbara** [comment]
@ZoriaRPG what software do you need on 10.11? I use a Mac fulltime for dev at work and home and have done some ZC dev on Mac in the past.

**Comment by EmilyV99** [comment]
OSX support is dead, as they no longer support 32-bit applications.
