### ISSUE TITLE
ROMView: Various Issues

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#67]
Selecting the menu option ''File->ROM File Types instantly crashes RV.

Changing the file type from the default SNES ROMs to anything else scrambles the UI:
    * UI elements are not drawn int he priper locations, and order. 
    * ZQuest has the same problem, from the new UI backends. 
Load Palette does not support ZPL files? -- What does it support?
File output ( bitmaps ) are solid blue.

**Comment by evouga** [comment]
> Selecting the menu option ''File->ROM File Types instantly crashes RV.

I wasn't seeing a crash, but I fixed an infinite hang.

> Changing the file type from the default SNES ROMs to anything else scrambles the UI:
* UI elements are not drawn int he priper locations, and order.

Fixed in Romview.

I'm not seeing the same problem during file selection in ZQ. If this is still happening, please open a new issue.

>  Load Palette does not support ZPL files? -- What does it support?
I'm not very familiar with Romview, but ZST palettes and image files, it seems. 

>  File output ( bitmaps ) are solid blue.

Is this incorrect? Or is it just that the palette is different than your image viewer expects? I don't see anything in the save code that has changed recently, unless Allegro has changed how they save bitmaps. If you can confirm that the save behavior is incorrect, please create a new issue and I will look into it.
