### ISSUE TITLE
Restore Linux support

### ISSUE THREAD

**Issue by mlimber** [ZQuestClassic/ZQuestClassic#717]
I tried cloning the repo and building on Linux to no avail. It used to work. I'm potentially willing to get it back to working on Linux again if there is support for that in the community. If so, can you give me any hints about where and why it broke and if there are any existing plans to fix it? I have some guesses based on the last Linux release (2.50.2), but I bet someone here knows.

**Comment by zoharion** [comment]
It depends which version of ZC you want to build. It's possible to build the 2.55 version, but it's more complicated. The 2.53.1 version it the easiest to compile for now. First you have to install the 32 bit version of allegro4 that comes with allegro.h from your distro and add the following lines to the CMakeLists.txt file : include_directories(/usr/include/allegro/include) under the headers section and add close to the line 139: link_directories(/usr/lib32 ./libs/linux) and add_compile_options("-fpermissive") under add_compile_options("-m32"). This method works on Archlinux, but i think it should work with others distros. If you really want to build the newest version, after doing the steps above, you have to change some files of the source code, the compiler gives hints on how to do this like changing "return NULL" to "return" and so on.

Obs: If you want midi playback to work via  the rawmidi driver, please look at my post regarding the issue.

**Comment by l12436** [comment]
I have successfully compile linux version of zeldaclassic under branch 2.53-master with allegro 4.4.3
due to 4.4.2 under ubuntu 20.04 will compile failed.
1. 64bit zeldac is not working. it must 32bit.
2. I use some of the library from allegro like loadpng, jpgal due to the code provide under 2.53-master will compile failed.
3. sound is still cracking with unknown reason, and play way more faster.
4. I have done a script just for compile zeldac, the original compile method under zeldac is not working under ubuntu 20.04

**Comment by connorjclark** [comment]
Is there a reason you didn't try to compile from the main branch? I don't anticipate a lot more work to make that functional. I plan to take a crack at it later this month.

**Comment by l12436** [comment]
because the 2.55-master will has some weird c++ error that I could not fixed under gcc.
so I just decide to build from the old branch.
something like "has invalid argument list"

---update---
ok, that only happened when build under x64
I am now build under x86 the error seems not happened for now.

**Comment by l12436** [comment]
Finally after some modfiy and fix compiler error. I built 2.55-master successfully under ubuntu 20.04...
some of the implement is not working under gcc 9.4.0
1. buffer overflow error will show up due to -Werror=format. I ignore it by remove the -Werror=format
2. some major issue is gcc 9.4 linker show error that `std::tmpnam` is not safe, please using `mkstemp()` or `tmpfile()`. But after reading document, it different from `tmpnam`. I just change to C version of `tmpnam()`, then the error gone.
3. missing `memory` include in `src/zc/title.cpp`, `src/zc/replay.cpp`
4. missing `ctime` include in `src/zc/replay.cpp`
5. `BUILD_SOUND_LIBS_FROM_SOURCE` should be `ON` or it will constant show some gme structure error
6. some compile error not in `ZeldaClassic` but in library `dumb` source code that is in _deps/dumb_external-src/include/dumb.h it using `-42` on unsigned int causing compiler error. I translate it to positive number `0xFFFFFFFFFFFFFFD6UL` prevent error

**Comment by connorjclark** [comment]
Next nightly will have an Ubuntu release.

**Comment by ZoriaRPG** [comment]
I run Debian 32, not Ubuntu. LmK if you want me to try to build either
branch and test them. That will also give you Debian bins, should they work.

As far as I recall, the audio issues are rooted in kernel drivers (ALSA
depreciation).
