### ISSUE TITLE
Item Editor Attributes Not Updating

### ISSUE THREAD

**Issue by gwx** [ZQuestClassic/ZQuestClassic#72]
When you change the class of an item in the item editor, the attribute labels and text box enabledness are not updated. You have to close the dialog and reopen it again.

This did properly work in 2.5, but I'm not sure when the bug was introduced.

**Comment by ZoriaRPG** [comment]
This was introduced with the new back-end, and with the DIALOG dialog_cpy stuff. The odd part, is that it is visually refreshing with static data. By this, i mean that you can see the dialogue redraw, but the values are not updating, and I am not certain why.

@DD, when you fix this, please put in some comments on what you change and why, so that I know in the future what this was missing. I tried inserting an additional call to setLabels(), but it did not work.  

I think that it only needs a call to that somewhere, but I'm not sure where.

**Comment by ZoriaRPG** [comment]
P.S. I don;t think that the present 'winking out; for a frame when you change an itemclass is intended, either.

**Comment by evouga** [comment]
> I think that it only needs a call to that somewhere, but I'm not sure where.

I'll take a look in a few days, but it's probably not that simple...

> please put in some comments on what you change and why, so that I know in the future what this was missing.

These GUI issues are a nasty consequence of the way it was originally implemented. All GUI elements are statically allocated at program start; this is a problem since positions, sizes, etc need to change depending on the current resolution and "mode" (big vs small) of the GUI.

Previously it was impossible to change resolutions while ZQuest was running, so there was code to swap in the positions, sizes, fonts, etc. once when ZQuest began if it was started in "big" mode. This no longer works when the resolution can change at any time, so what the code does now is to create a new copy of each window's data at the time the window is invoked, and dynamically resizing/positioning/etc the window based on the current display settings.

This works for the most part, but there are parts of the code that reference the hard-coded static window data instead of looking at or modifying the currently-shown, properly-resized copy of the window. All such instances in the code need to be found and fixed.

**Comment by ZoriaRPG** [comment]
Do you think that you can add a backend function to do UpdateDialogue(*DIALOG) so that it is simpler to write these in the future? Getting dialogues to refresh when data is changed is going to be very important in the semi-near future.

**Comment by evouga** [comment]
Not really? Each dialog is coded from scratch; jwin has no notion of any kind of model backing the dialog. Each window listens for mouse clicks, keyboard events, etc and explicitly updates ZQ data structures appropriately.

> Getting dialogues to refresh when data is changed

Of course this is possible, you just have to write the code to change the UI elements and then tell jwin to redraw them. You can see in `setLabels()` how this is done for the item editor (and that it's a rather big mess).

**Comment by evouga** [comment]
In any case the update issue is fixed.
