### ISSUE TITLE
Sound doesn't work on Linux Mint

### ISSUE THREAD

**Issue by Bulba413** [ZQuestClassic/ZQuestClassic#870]
I've made sure that Disable Sound is off for both the player and creator, and I've checked OGG, NSF, GBS, and MIDI BGM, as well as SFX. None of them work. I checked the Flatpak, latest release on the Releases tab and even the latest Actions artifact, and it was the same for all three.

Pretty much all other aspects work without issue, it's just the sound that's broken.

It's not really a big deal because most quests don't rely on audio a lot, but it is kind of annoying.

**Comment by connorjclark** [comment]
Do sound effects (like enemy attacks or swing your weapon or the beep when moving around the title screen select) also not work?

Edit: just saw you mentioned SFX busted too

Can you share the allegro.log? First delete it, then open up the Zelda player and move around the title select screen a bit, then close and send what the log is

**Comment by Bulba413** [comment]
[Here's the log.](https://github.com/ArmageddonGames/ZQuestClassic/files/12306768/allegro.log)

**Comment by connorjclark** [comment]
Nothing interesting in there.

I'll have to load a Mint VM and investigate further.

**Comment by Bulba413** [comment]
I found a partial fix. I manually opened up the allegro5.cfg file and changed the ALSA sound device from default to /dev/snd, which made the SFX and most music work, with the only problem being that Midi specifically was still broken.

**Comment by connorjclark** [comment]
Glad you found a solution! I'll add it to a README for linux users to try that if their sound is not working.

MIDI is special, since it requires either real MIDI hardware or a software synthesizer. Our Windows and OSX backends provide a software synthesizer using the OS utilities, but AFAIK on Linux there is no such common utility so you need to provide one yourself. This may be enough instruction to get MIDI functioning: https://www.purezc.net/forums/index.php?showtopic=78117&p=1073401

If an external contributor would like to help out and integrate Timidity ... Linux users would appreciate it :)
