### ISSUE TITLE
SFXBackend is Missing Functions

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#88]
When DD moved the sfx stuff to the new backend, he missed continue_sfx() and adjust_sfx(). I believe that the former restarted a sound from its first bit (in a loop), and adjust_sfx() did some interesting things. We are missing a few audio effects/functions that were available before, and we still need to update our enhanced audio libs, too. 

Stuff to set MIDI loops and whatnot seems to be absent.

**Comment by ZoriaRPG** [comment]
Here is a quick git push of the backend file with a comment block that illustrates all of the missing instructions.

If these have analogues somewhere, please indicate /where/ so that i can use them. Thank you. -Z

https://github.com/ZoriaRPG/ZeldaClassic/tree/MissingSFXBackend

**Comment by evouga** [comment]
What do you mean there are "missing instructions"?

I changed around and consolidated some functions, but that shouldn't matter... the behavior of ZC quests should be identical as before. Do you have an example .qst with behavior that is now broken?

**Comment by evouga** [comment]
> Stuff to set MIDI loops and whatnot seems to be absent.

None of the MIDI code has (yet) been refactored into the backend.

**Comment by evouga** [comment]
To be clear, the absence of these functions is intentional, as the entire sound engine was refactored.

1. If the changes broke old quests, that is a bug. If you explain the scenario where an old quest breaks, I'll fix it.

2. If you are trying to add features to the SFX engine, you should do so by first studying the new API and making sure it cannot already do what you are trying to do, and if not, modifying the new API (without breaking the sound engine, obviously).
