### ISSUE TITLE
Unable to load enhanced music (Linux Mint - Flatpak v2.55.3)

### ISSUE THREAD

**Issue by ghost** [ZQuestClassic/ZQuestClassic#932]
So every time I attempt to add in enhanced music, I'm met with this error, even if the requirements are met(i.e. music actually being in the same folder as the quest or in the music folder)

![image](https://github.com/ZQuestClassic/ZQuestClassic/assets/8013951/10ee383b-df52-4336-b1e4-41456dd5abed)

It feels like it's just not seeing that it's in the correct location and just gives the error regardless of where I place the music files.

**Comment by connorjclark** [comment]
It's possible the file is not loading correctly for some other reason. This error detection here does not distinguish between failing to load the music and failing to find the file.

1) can you play this file from the Etc > Media > Play music dialog?
2) in the dmap music tab, can you load any other music file (like the Classic.nsf you should see in the ZC installation folder)?

**Comment by ghost** [comment]
classic.nsf loads in ect > media > play music but does not play any music, it's still silent, however I get the same exact error in the dmap music tab when trying to set the enhanced music to it.

**Comment by connorjclark** [comment]
Ah, so it is indeed failing to load tracker files. It's likely finding it just fine.

I'll improve the error message here, and once I've got my Linux machine working again I'll debug it further. I do know it was working when I tried in Ubuntu via a VM... but I am going to install Mint and see. Feel free to ping me in a week if I haven't given an update by then.

**Comment by ghost** [comment]
so it's been a week, any progress?

**Comment by connorjclark** [comment]
Nope. I had to order a usb drive to install Mint, and this morning I learned I can't get any of my wireless mouses to work so waiting for a wired mouse to ship.

Should get a chance to work on this during the weekend.

**Comment by ghost** [comment]
Ah okay, sorry for all the hassle!

**Comment by connorjclark** [comment]
All set up now with Mint.

Strangely I found that I couldn't even get flatpak to run. I was able to build locally and confirm these `.nsf` music files worked, so that's a good sign.

I know of a few improvements that should be made to the flatpak distribution, perhaps after resolving them we'll find that music works.

If you'd like to build locally, I've just [updated the instructions](https://github.com/ZQuestClassic/ZQuestClassic/blob/main/docs/building.md#building-on-linux) for how to do so on for Mint (though you should use `--config Release` instead of `--config Debug`). You can use the latest 3.0 prerelease by building from the `main` branch, or stick to 2.55 by using the `releases/2.55` branch.

**Comment by connorjclark** [comment]
Good news.

I got the flatpak ZC running w/ `LIBGL_ALWAYS_SOFTWARE=1 flatpak run com.zquestclassic.ZQuest`. Not sure if related to a mistaken choice by the Mint/Ubuntu developers, or related to my nvidia card. Found this workaround by looking for other allegro apps and found [this one](https://github.com/alemart/opensurge/issues/116).

So I was finally able to run the flatpak, and I play classic.nsf, and oh boy that was some hot garbled garbage. Sounded satanic.

I'm making progress reworking the flatpak build to build-from-source, rather than plucking a prebuilt binary we make from GitHub actions, which was problematic (apparently it's possible to publish prebuilt binaries via flatpak, but not how I was doing it, and probably requires a few full-time developers to truly do correctly). As I mentioned before the music plays just fine when built locally like this, so I suspect this will resolve your music issues as well.

**Comment by connorjclark** [comment]
2.55.4 may resolve this for you. Let me know!

If it is not available to you from the software manager yet, you can grab it here:

```
flatpak install --user https://dl.flathub.org/build-repo/113811/com.zquestclassic.ZQuest.flatpakref
```

**Comment by ghost** [comment]
Well I gotta load up zquest via software manager now, but everything works! Thanks for the fix! :)

**Comment by connorjclark** [comment]
Nice, happy questing!
