### ISSUE TITLE
No number of seconds displayed when previewing enhanced music on dmap screens? (EndeavourOS Linux - v2.55.6 - Flatpak)

### ISSUE THREAD

**Issue by ghost** [ZQuestClassic/ZQuestClassic#998]
Not certain if it's due to me switching linux distros or of it's due to the v2.55.6 update, but previewing enhanced music on the dmap window no longer shows how many seconds in the preview it is.

![image](https://github.com/user-attachments/assets/ba3813e8-ad60-41c4-9225-12d3d1c0c041)

Enhanced Music still works fine, however looping enhanced music is now more difficult due to it not showing the time.

**Comment by EmilyV99** [comment]
Several dialogs broke in small ways, as during a refactor, an `onTick` function was accidentally removed from being called. Already caught and fixed by https://github.com/ZQuestClassic/ZQuestClassic/commit/dd0bf95ce3a58bec04c89e6ffa14b6d424659b22 in the `main` branch; still needs to be backported, should be fixed for 2.55.7

**Comment by connorjclark** [comment]
yup (closing as no action left)
